# Generated by Django 2.1.7 on 2019-03-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DownloadCount', models.IntegerField(default=0, verbose_name='访问次数')),
                ('code', models.CharField(max_length=8, verbose_name='code')),
                ('path', models.CharField(max_length=32, verbose_name='下载路径')),
                ('name', models.CharField(default='', max_length=32, verbose_name='文件名')),
                ('FileSize', models.CharField(max_length=10, verbose_name='文件大小')),
                ('PCIP', models.CharField(default='', max_length=32, verbose_name='IP地址')),
            ],
            options={
                'verbose_name': 'download',
                'db_table': 'down_load',
            },
        ),
    ]
