# Generated by Django 2.1.7 on 2019-03-29 12:35

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.IntegerField(primary_key=builtins.id, serialize=False)),
                ('tag', models.CharField(max_length=32, verbose_name='标签管理')),
            ],
        ),
    ]
