# Generated by Django 2.1.3 on 2019-03-29 14:10

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.IntegerField(primary_key=builtins.id, serialize=False)),
                ('admin_user', models.TextField(default='', max_length=10, verbose_name='用户管理')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(primary_key=builtins.id, serialize=False)),
                ('title', models.CharField(default='', max_length=20, verbose_name='文章标题')),
                ('content', models.TextField(default='', verbose_name='文章内容')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=builtins.id, serialize=False)),
                ('category', models.CharField(max_length=32, verbose_name='分类管理')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.IntegerField(primary_key=builtins.id, serialize=False)),
                ('tag', models.CharField(max_length=32, verbose_name='标签管理')),
            ],
        ),
    ]
