# Generated by Django 2.1.3 on 2019-03-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gzyblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='admin_user',
            field=models.CharField(default='', max_length=10, verbose_name='用户管理'),
        ),
    ]
