# Generated by Django 2.1.7 on 2019-03-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gzyblog', '0002_adminuser_article_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default='', verbose_name='文章内容'),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=20, verbose_name='文章标题'),
        ),
    ]
