# Generated by Django 2.1.3 on 2019-03-29 14:18

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gzyblog', '0002_auto_20190329_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.IntegerField(primary_key=builtins.id, serialize=False)),
                ('user_name', models.CharField(max_length=20, verbose_name='用户名')),
            ],
        ),
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
