# Generated by Django 2.1.3 on 2019-03-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gzyblog', '0003_auto_20190329_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default='', max_length=32, verbose_name='分类管理'),
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.CharField(default='', max_length=32, verbose_name='标签管理'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='ip',
            field=models.GenericIPAddressField(default='', protocol='ipv4'),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
