# Generated by Django 2.1.3 on 2019-03-30 07:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gzyblog', '0006_auto_20190330_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='abstract',
            field=models.TextField(default='', max_length=100, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 30, 7, 30, 1, 723638, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
