# Generated by Django 2.1.7 on 2019-03-30 09:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gzyblog', '0007_auto_20190330_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 30, 9, 10, 1, 336631, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
