# Generated by Django 2.1.7 on 2019-03-30 10:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gzyblog', '0009_auto_20190330_1815'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 30, 10, 16, 33, 900657, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
